### ISSUE TITLE
Missing some non-utility patents in bulk download files

### ISSUE THREAD

**Issue by crew102** [CSSIP-AIR/PatentsView-DB#20]
As reported by @mustberuss in #5, it looks like the bulk data files are missing some non-utility patents. For example, patent number  RE46653 is indexed in whatever backend db the PatentsView API is currently using:

```r
library(patentsview)
res <- search_pv('{"_eq":{"patent_number":"RE46653"}}')
res$query_results
#> #### Distinct entity counts across all downloadable pages of output:

#> total_patent_count = 1
```

...But this patent is not present in the bulk data files.

**Comment by sarahkelley** [comment]
@crew102 Thanks for pointing this out! We will look into the issue and get back to you as soon as we can!

**Comment by sarahkelley** [comment]
@crew102 I can't replicate your error - I can find this file in the patents bulk download file and the count of patents in the bulk downloads matches the count of patents in the backend DB too.  Are you looking in a different bulk download file?

I do note that this is one of the patents that is missing from the CPC table (see: https://github.com/CSSIP-AIR/PatentsView-DB/issues/7), so it won't be in the CPC bulk download file. We are working on the patents missing from the CPC files and will respond to that issue once that is fixed.

**Comment by crew102** [comment]
I can't seem to get to the bulk data download page right now..Also the API isn't responding to my requests, so it's kinda hard to figure out what's going on at the moment.

**Comment by sarahkelley** [comment]
Thanks for your patients, we are having a volume of requests issue right now and are working on fixing it! Hopefully things should be back in operation soon!

**Comment by mustberuss** [comment]
@sarahkelley the issue I mentioned in #5 is that the bulk cpc zip file only contains utility patents.  I emailed the uspto and was told there is no bulk cpc file for plants and reissued patents. As a result patentsview is missing cpcs for all reissued patents and plant patents with cpcs (roughly half have been assigned cpcs)

**Comment by sarahkelley** [comment]
@mustberuss Ah, I see! That makes sense.

**Comment by sarahkelley** [comment]
@crew102 Yes, the missing patent issue should be entirely resolved in the December data and the bulk downloads were most recently updated using the December data (the website should now reflect that change also). 

I am going to close this issue now, but please reach out again if you are still finding any issues!
