### ISSUE TITLE
Api returns data for withdrawn patents

### ISSUE THREAD

**Issue by mustberuss** [CSSIP-AIR/PatentsView-DB#21]
As @crew102 encountered in issue #5, the api is returning data for withdrawn patents.  A step should be added to the data load that purges data from all tables associated with withdrawn patents.  After an initial purge, it would just be purging patents withdrawn since the previous load.  Here's a sampling of patents from http://www.uspto.gov/patents-application-process/patent-search/withdrawn-patent-numbers that the api returns data for: [{"patent_number":["RE44868","RE45507","RE46094","PP20696","D793197","9304413","9305675","9305811","9305986","9305991","9306004","9306035","9306121","9306204","9306343","9306356","9306404","9306408","9306410","9306484","9306536","9306821","9306842","9306846","9306847","9306931","9307064","9307254","9307661"]}](http://www.patentsview.org/api/patents/query?q=%7B%22patent_number%22%3A%5B%22RE44868%22%2C%22RE45507%22%2C%22RE46094%22%2C%22PP20696%22%2C%22D793197%22%2C%229304413%22%2C%229305675%22%2C%229305811%22%2C%229305986%22%2C%229305991%22%2C%229306004%22%2C%229306035%22%2C%229306121%22%2C%229306204%22%2C%229306343%22%2C%229306356%22%2C%229306404%22%2C%229306408%22%2C%229306410%22%2C%229306484%22%2C%229306536%22%2C%229306821%22%2C%229306842%22%2C%229306846%22%2C%229306847%22%2C%229306931%22%2C%229307064%22%2C%229307254%22%2C%229307661%22%5D%7D)

**Comment by killahjones** [comment]
Good idea - we will add this to our growing data update list. Thanks!
