### ISSUE TITLE
Missing CPC codes

### ISSUE THREAD

**Issue by crew102** [CSSIP-AIR/PatentsView-DB#5]
It looks like the PatentsView data is missing CPC codes for some patents. If I search my PatentsView database for utility patents patents that don't have any CPC cods assigned to them, I come up with roughly 20,000 patents. I checked Google Patents for a few of these and found that they do indeed have CPC codes (at least according to Google). Roughly half of the 20,000 patents missing CPC codes were published in 2017. Here are a few examples:

``` r
library(patentsview)
library(jsonlite)

patents_no_cpcs <- c(
  "9027130", # published in 2015, https://www.google.com/patents/US9027130
  "9027549", # published in 2015, https://www.google.com/patents/US9027549
  "9494444", # published in 2016, https://www.google.com/patents/US9494444
  "9723528"  # published in 2017, https://www.google.com/patents/US9723528
)

query <- sprintf('{"patent_number":%s}', toJSON(patents_no_cpcs))

pv_out <- search_pv(
  query = query, 
  fields = get_fields("patents", c("patents", "cpcs"))
)

# These 4 patents exist according to PatentsView:
pv_out$data$patents$patent_title 
#> [1] "Systems and methods for unauthorized activity defense"                                                         
#> [2] "Battery management for a breathing assistance system"                                                          
#> [3] "Data acquisition apparatus, data acquisition system and method of acquiring data"                              
#> [4] "Methods and apparatus to provide packet switched service continuity during circuit switched fallback operation"

# ...But none of them have CPC data:
all(is.na(unlist(pv_out$data$patents$cpcs)))
#> [1] TRUE
```

**Comment by sarahkelley** [comment]
Thanks for pointing out this issue to us! We will look into what is causing this and get back to you when we have figure out what has happened and/or have fixed it!

**Comment by mustberuss** [comment]
@crew102,

I don't know what the original issue was but the fourth patent is displaying 2 cpcs now.  The first three patents have been withdrawn so they don't have entries in newer bulk cpc files. Their google links are 404's now and they probably should be removed from the patentsview database.

http://patft.uspto.gov/netacgi/nph-Parser?patentnumber=9027130
http://patft.uspto.gov/netacgi/nph-Parser?patentnumber=9027549
http://patft.uspto.gov/netacgi/nph-Parser?patentnumber=9494444
http://www.uspto.gov/patents-application-process/patent-search/withdrawn-patent-numbers

Other Problems:

There is also a problem where the bulk cpc files used to populate patentsview only contain utility patents.  I verified with IPD@uspto.gov that there is no bulk cpc file available for plant patents (about half have cpcs) and reissued utility patents.  Here are examples of each that have cpcs on their uspto pages but not in patentsview http://patft.uspto.gov/netacgi/nph-Parser?patentnumber=PP27262 http://patft.uspto.gov/netacgi/nph-Parser?patentnumber=RE46653

The bulk cpc files have a fixed format where the patent number is 7 digits.  This will be a problem soon when the 10 millionth utility patent is issued!

**Comment by crew102** [comment]
@sarahkelley, is the issue that I filed re: missing CPC closed? As @mustberuss mentioned, one of the patents that I gave as an example of patents missing CPC codes (patent number 9723528) now actually has CPC codes assigned to it according to PatentsView.

**Comment by sarahkelley** [comment]
@crew102  Yes, we did fix that issue! I'll close it now!
