### ISSUE TITLE
multiple inventor locations

### ISSUE THREAD

**Issue by dhquimby** [CSSIP-AIR/PatentsView-DB#8]
The location_inventor table has multiple locations per inventor -- but it doesn't associate particular patents with particular locations. For geographic analysis, additional granularity would be helpful -- it would be helpful to know which of the inventor's patents are associated with each location (which of the inventor's locations are associated with each patent).

**Comment by sarahkelley** [comment]
That sounds like a great idea, we will add it to the list of requests that we keep and let you know if we plan to add this feature! Thanks for the feedback!
